Refactor paths to use rcpputils filesystem helper
ament/ament_index pull request #46
Opened 2020-02-07 17:45 UTC by piraka9011

The purpose of this refactor is to provide proper path support for both Linux and Windows systems. The previous implementation hard codes forward slashes which are not the convention on Windows systems. Using the filesystem helper in `rcpputils` resolves this.
Using `rcpputils` pulls in the dependency on `rcutils` for this package as well.

I didn't change on the return signatures for the methods to avoid breaking any previous workflows.

Resolves #45 

Signed-off-by: Anas Abou Allaban <allabana@amazon.com>

2020-02-07 18:27 UTC, wjwwood approved these changes
Other than some trivial feedback on include statement order, lgtm.

I don't think there's any issue with adding `rcpputils` as a dependency of `ament_index_cpp`.

2020-02-07 18:27 UTC, wjwwood commented on ament_index_cpp/src/get_package_share_directory.cpp
> +#include "rcpputils/filesystem_helper.hpp"
nitpick: I think `#include "ament_index_cpp/get_package_prefix.hpp"` should be in its own block after the include from `rcpputils`, based on this:

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

And the fact that we often add a blank line between "Other libraries' .h files." and "Your project's .h files.".

2020-02-07 18:27 UTC, wjwwood commented on ament_index_cpp/src/get_resource.cpp
> +#include "rcpputils/filesystem_helper.hpp"
nitpick: and here

2020-02-07 18:27 UTC, wjwwood commented on ament_index_cpp/src/get_resources.cpp
> +#include "rcpputils/filesystem_helper.hpp"
nitpick: and here

2020-02-07 18:27 UTC, wjwwood commented on ament_index_cpp/src/has_resource.cpp
> +#include <rcpputils/filesystem_helper.hpp>
There should definitely be a blank line between the system headers block and other library headers.

2020-02-07 18:35 UTC, piraka9011 commented
@wjwwood nits resolved!

2020-02-07 19:46 UTC, wjwwood approved these changes
lgtm

2020-02-07 19:48 UTC, wjwwood commented
CI:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9277)](http://ci.ros2.org/job/ci_linux/9277/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4964)](http://ci.ros2.org/job/ci_linux-aarch64/4964/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7590)](http://ci.ros2.org/job/ci_osx/7590/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9198)](http://ci.ros2.org/job/ci_windows/9198/)
* Windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=84)](http://ci.ros2.org/job/ci_windows-container/84/)

2020-02-07 20:02 UTC, wjwwood commented
Looks like a compiler error on Windows:

```
11:58:21 [7.265s]   has_resource.cpp
11:58:21 [7.984s] C:\J\workspace\ci_windows\ws\src\ament\ament_index\ament_index_cpp\src\get_resources.cpp(75,58): error C2440: 'initializing': cannot convert from 'rcpputils::fs::path' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' [C:\J\workspace\ci_windows\ws\build\ament_index_cpp\ament_index_cpp.vcxproj]
11:58:21 [8.578s] C:\J\workspace\ci_windows\ws\src\ament\ament_index\ament_index_cpp\src\get_resources.cpp(75,58): message : No constructor could take the source type, or constructor overload resolution was ambiguous [C:\J\workspace\ci_windows\ws\build\ament_index_cpp\ament_index_cpp.vcxproj]
```

2020-02-07 20:13 UTC, zmichaels11 requested changes

2020-02-07 20:13 UTC, zmichaels11 commented on ament_index_cpp/src/get_resources.cpp
> +    std::string pattern = rcpputils::fs::path{path} / "*";
```suggestion
    const auto pattern = (rcpputils::fs::path{path} / "*").string();
```

2020-02-07 20:14 UTC, zmichaels11 commented
Can I stop the rest of the CI since windows failed?

2020-02-07 20:16 UTC, wjwwood commented
Yeah, feel free to do that.

2020-02-07 23:00 UTC, piraka9011 commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9283)](http://ci.ros2.org/job/ci_linux/9283/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4970)](http://ci.ros2.org/job/ci_linux-aarch64/4970/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7596)](http://ci.ros2.org/job/ci_osx/7596/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9203)](http://ci.ros2.org/job/ci_windows/9203/)
* Windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=88)](http://ci.ros2.org/job/ci_windows-container/88/)

2020-02-07 23:59 UTC, zmichaels11 approved these changes

2020-02-10 16:53 UTC, piraka9011 commented
@wjwwood it looks like the builds are unstable due to an unrelated issue (flake8/copyright). Should I re-run CI?

2020-02-10 19:16 UTC, wjwwood commented
> Should I re-run CI?

Not yet, I'm looking into it.

2020-02-10 19:54 UTC, wjwwood commented
@piraka9011 can you rerun? I think we've reverted the offending change.

2020-02-10 21:42 UTC, wjwwood commented
Re-running my CI from several comments above (not sure if the settings are similar to @piraka9011's):

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9297)](http://ci.ros2.org/job/ci_linux/9297/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4981)](http://ci.ros2.org/job/ci_linux-aarch64/4981/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7609)](http://ci.ros2.org/job/ci_osx/7609/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9220)](http://ci.ros2.org/job/ci_windows/9220/)
* Windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=105)](http://ci.ros2.org/job/ci_windows-container/105/)

2020-02-10 21:48 UTC, piraka9011 commented
> Re-running my CI from several comments above (not sure if the settings are similar to @piraka9011's):

They are the same. I wanted to run the CI at the end of the day since it's a lot of packages and I didn't want to hog the queue.

2020-02-10 21:50 UTC, wjwwood commented
Ok, no worries, that was thoughtful of you, but I already started them, so we'll just let them run.

2020-02-11 00:05 UTC, merged

2020-02-21 20:09 UTC, clalancette commented
For reasons I don't fully understand, it looks like this PR broke the packaging jobs on Linux.  For instance, if you download any packaging job from https://ci.ros2.org/view/packaging/job/packaging_linux/ since Feb 10th, and try to compile https://github.com/ros-perception/image_common/tree/ros2 and https://github.com/ros-perception/image_pipeline/tree/ros2 after sourcing it, you'll get:

```
CMake Error in CMakeLists.txt:                       
  Imported target "ament_index_cpp::ament_index_cpp" includes non-existent
  path

    "/home/jenkins-agent/workspace/packaging_linux/ws/install/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

when trying to build `image_proc`.  I tried reverting just this change in https://ci.ros2.org/job/ci_packaging_linux/296/ , and things went back to working.  @piraka9011 can you look into it?  In the meantime, I'm going to propose a revert so we can get the packaging jobs working again.

2020-02-22 01:09 UTC, piraka9011 commented
@clalancette Sure, I'm not sure why this it occurred and why CI didn't catch it but I can look into it when I get the chance.